# Generated by Django 5.1 on 2024-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the Campaign", max_length=50),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the campaign was created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When the campaign was modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaigns",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("trainer", "trainer"), ("lead", "lead")],
                        default="trainer",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="full name of the member", max_length=250
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the member was created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When the member details was modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "Members",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Task name", max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("choices", "choices"),
                            ("simple life cycle", "simple life cycle"),
                        ],
                        default="choices",
                        max_length=50,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When the task was modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasks",
                "ordering": ["-created"],
            },
        ),
    ]
