# Generated by Django 5.1 on 2024-09-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_task_reviewed_by_task_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Campaign",
                to="home.campaign",
            ),
        ),
    ]
