# Generated by Django 5.1 on 2024-09-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_campaign_id_alter_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["-created"], "verbose_name": "Campaign"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["-created"], "verbose_name": "Member"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created"], "verbose_name": "Task"},
        ),
    ]
